### ISSUE TITLE
Error loading service

### ISSUE THREAD

**Issue by splendid25** [skylex/xbmc-betaseries#15]
Hi, the version 1.0.9 has a problem at startup :

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'tvdbepid' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 504, in <module>
                                                Main()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 79, in __init__
                                                self._service_setup()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 88, in _service_setup
                                                self._get_settings()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 105, in _get_settings
                                                self.Player = MyPlayer(action = self._service_betaserie, service = service)
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 309, in __init__
                                                self.ScanRecentlyadded()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 404, in ScanRecentlyadded
                                                episode = self._get_episode_info( episode['episodeid'], -1, self.Play)
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 437, in _get_episode_info
                                                if not tvdbepid:
                                            UnboundLocalError: local variable 'tvdbepid' referenced before assignment
                                            -->End of Python script error report<--

**Comment by skylex** [comment]
I've just pushed version 1.0.10 which should correct this issue. tell me if it's OK

**Comment by splendid25** [comment]
There is another error now :

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'bool' object does not support item assignment
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 506, in <module>
                                                Main()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 79, in __init__
                                                self._service_setup()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 88, in _service_setup
                                                self._get_settings()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 105, in _get_settings
                                                self.Player = MyPlayer(action = self._service_betaserie, service = service)
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 309, in __init__
                                                self.ScanRecentlyadded()
                                              File "/home/kodi/.kodi/addons/service.betaseries.com/betaseries.py", line 405, in ScanRecentlyadded
                                                episode[2]=-1
                                            TypeError: 'bool' object does not support item assignment
                                            -->End of Python script error report<--

**Comment by skylex** [comment]
Hi, this one should be fixed too now, let me know if you see another bug ;)

**Comment by anthonyCarigny** [comment]
I got the same issue in version 4.0.9.
`2020-02-09 11:07:27.839 T:11300   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'tvdbepid' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\Touny\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 504, in <module>
                                                Main()
                                              File "C:\Users\Touny\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 79, in __init__
                                                self._service_setup()
                                              File "C:\Users\Touny\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 88, in _service_setup
                                                self._get_settings()
                                              File "C:\Users\Touny\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 105, in _get_settings
                                                self.Player = MyPlayer(action = self._service_betaserie, service = service)
                                              File "C:\Users\Touny\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 309, in __init__
                                                self.ScanRecentlyadded()
                                              File "C:\Users\Touny\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 404, in ScanRecentlyadded
                                                episode = self._get_episode_info( episode['episodeid'], -1, self.Play)
                                              File "C:\Users\Touny\AppData\Roaming\Kodi\addons\service.betaseries.com\betaseries.py", line 437, in _get_episode_info
                                                if not tvdbepid:
                                            UnboundLocalError: local variable 'tvdbepid' referenced before assignment
                                            -->End of Python script error report<--`
