### ISSUE TITLE
ERROR: service.subtitles.betaseries: HTTPError = 400

### ISSUE THREAD

**Issue by d3smo** [skylex/xbmc-betaseries#17]
I've got this error using service.subtitles.betaseries 1.0.7 on Kodi (17.6 Git:20171114-a9a7a20). Platform: Windows NT x86 32-bit
(the plugin still works in Kodi 16.1)

11:31:59.101 T:5836   ERROR: service.subtitles.betaseries: HTTPError = 400
11:31:59.102 T:5836   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\PCHC\AppData\Roaming\Kodi\addons\service.subtitles.betaseries\service.py", line 444, in <module>
                                                search_subtitles(item)
                                              File "C:\Users\PCHC\AppData\Roaming\Kodi\addons\service.subtitles.betaseries\service.py", line 224, in search_subtitles
                                                showid = json.loads(get_url(showurl))["show"]["id"]
                                              File "C:\Users\PCHC\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\__init__.py", line 488, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Users\PCHC\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "C:\Users\PCHC\AppData\Roaming\Kodi\addons\script.module.simplejson\lib\simplejson\decoder.py", line 389, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--

**Comment by skylex** [comment]
Hi, Windows NT, are you from the past? ;)
Anyway, the error may be fixed now.
Thanks for the report and let me know if it's solved.
