### ISSUE TITLE
Bug Python

### ISSUE THREAD

**Issue by CATAM22** [skylex/xbmc-betaseries#23]
Hello à tous,

Depuis la v18 kodi, et la 1.0.12 betaseries agent, plus aucun épisode marqué comme vu (idem en désactivant, idem en retirant les màj auto et l'ajout des nouvelles séries).
Tout ce que j'ai dans le log c'est ça :

the python script \Kodi\addons\service.betaseries.com\betaseries.py" has left several classes in memory that we couldn't clean up.

Note : l'agent se charge, par contre pas popup après chaque visionnage pour dire "marqué comme vu". Je n'ai fait aucun changement de conf ou autre ni sur le plugin si sur Kodi Leia. Une idée ?

Merci.

**Comment by CATAM22** [comment]
Next of log : 

service.betaseries.com: could not fetch episode's thetvdb_id
2019-06-03 20:16:23.959 T:1699230576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'bool' object does not support item assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.betaseries.com/betaseries.py", line 506, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/service.betaseries.com/betaseries.py", line 79, in __init__
                                                self._service_setup()
                                              File "/storage/.kodi/addons/service.betaseries.com/betaseries.py", line 88, in _service_setup
                                                self._get_settings()
                                              File "/storage/.kodi/addons/service.betaseries.com/betaseries.py", line 105, in _get_settings
                                                self.Player = MyPlayer(action = self._service_betaserie, service = service)
                                              File "/storage/.kodi/addons/service.betaseries.com/betaseries.py", line 309, in __init__
                                                self.ScanRecentlyadded()
                                              File "/storage/.kodi/addons/service.betaseries.com/betaseries.py", line 405, in ScanRecentlyadded
                                                episode[2]=-1
                                            TypeError: 'bool' object does not support item assignment
                                            -->End of Python script error report<--

Thanks.

**Comment by skylex** [comment]
Hello, c'est bizarre car j'ai Kodi 18 depuis plusieurs mois et aucun problème avec le plugin. C'est sur une série en particulier ou pas ?

**Comment by CATAM22** [comment]
Hello skylex.nope ça le fait sur toutes...

**Comment by CATAM22** [comment]
Bon ben reinstall fraîche 9.0.2 et 1.0.12:idem.le plugin se charge mais tag plus les épisodes...pffffff...je désespère...

**Comment by CATAM22** [comment]
Bon suite aux derniers test il doit y avoir un bug côté bdd...car le plugin marche pour les films...

**Comment by CATAM22** [comment]
Peut être une piste:hier il m'a retrouve the rain et m'a noté l'ajout...et il m'a rajouté la série neighbours que je ne connais pas...

**Comment by CATAM22** [comment]
Hello.bizarrement depuis le changement de scraper ça a l'air de repasser...j'ai pu en tagger 3 en auto...possible que ça soit le scraper qui merde et pas le tag de Kodi en lui même?
