### ISSUE TITLE
Betaseries subtitles - Could not find any subtitles

### ISSUE THREAD

**Issue by gaetan-petit** [skylex/xbmc-betaseries#8]
**Version:** 1.06

**Log:**

```
11:48:56 T:1768944704   DEBUG: StartScript - calling plugin Betaseries('plugin://service.subtitles.betaseries/','10','?action=search&languages=French&preferredlanguage=French')
11:48:56 T:1486877760  NOTICE: Thread LanguageInvoker start, auto delete: false
11:48:56 T:1768944704   DEBUG: WaitOnScriptResult - waiting on the Betaseries (id=18) plugin...
11:48:56 T:1486877760    INFO: initializing python engine.
11:48:56 T:1486877760   DEBUG: CPythonInvoker(18, /storage/.kodi/addons/service.subtitles.betaseries/service.py): start processing
11:48:57 T:1486877760  NOTICE: -->Python Interpreter Initialized<--
11:48:57 T:1486877760   DEBUG: CPythonInvoker(18, /storage/.kodi/addons/service.subtitles.betaseries/service.py): the source file to load is "/storage/.kodi/addons/service.subtitles.betaseries/service.py"
11:48:57 T:1486877760   DEBUG: CPythonInvoker(18, /storage/.kodi/addons/service.subtitles.betaseries/service.py): setting the Python path to /storage/.kodi/addons/service.subtitles.betaseries:/storage/.kodi/addons/script.module.simplejson/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/PIL:/usr/lib/python2.7/site-packages/gtk-2.0
11:48:57 T:1486877760   DEBUG: CPythonInvoker(18, /storage/.kodi/addons/service.subtitles.betaseries/service.py): entering source directory /storage/.kodi/addons/service.subtitles.betaseries
11:48:57 T:1486877760   DEBUG: CPythonInvoker(18, /storage/.kodi/addons/service.subtitles.betaseries/service.py): instantiating addon using automatically obtained id of "service.subtitles.betaseries" dependent on version 2.1.0 of the xbmc.python api
11:49:01 T:1486877760   DEBUG: service.subtitles.betaseries: deleting temp tree...
11:49:01 T:1486877760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.betaseries/service.py", line 408, in <module>
                                                shutil.rmtree(__temp__)
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 239, in rmtree
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/posixpath.py", line 71, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
                                            -->End of Python script error report<--
11:49:01 T:1968631808   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
11:49:02 T:1486877760    INFO: Python script stopped
11:49:02 T:1486877760   DEBUG: Thread LanguageInvoker 1486877760 terminating
11:49:02 T:1768944704   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
11:49:02 T:1768944704   ERROR: GetDirectory - Error getting plugin://service.subtitles.betaseries/?action=search&languages=French&preferredlanguage=French
```

**Comment by gaetan-petit** [comment]
@skylex I have no idea where the **/home/stephan/projects/** comes from :fearful:

**Comment by skylex** [comment]
I made a correction for this on all the subtitles plugins, thanks to chirel's help.
It was due to accents in the temp path's name.

**Comment by gaetan-petit** [comment]
@skylex thanks for this fix, hope I could help you again.
